"""
Add final cells to NASA ML training notebook
"""
import json

# Load notebook
with open('notebooks/02_NASA_ML_training.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Final cells
final_cells = [
    # Cell: Markdown - Test Evaluation
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 10. Final Evaluation on Test Set\n",
            "\n",
            "### Why Separate Test Set?\n",
            "\n",
            "- **Validation set**: Used during model selection/tuning\n",
            "- **Test set**: **Never seen during training** - gives unbiased performance estimate\n",
            "\n",
            "### What to Expect:\n",
            "- Test set contains **late-life data** (low RUL values)\n",
            "- This is the **most critical** period for prediction\n",
            "- Harder to predict than early life (more degradation variability)\n",
            "\n",
            "### Success Criteria:\n",
            "- **RMSE < 15%**: Excellent\n",
            "- **RMSE < 25%**: Good\n",
            "- **RMSE < 35%**: Acceptable\n",
            "- **R² > 0.7**: Strong predictive power\n"
        ]
    },
    
    # Cell: Code - Test evaluation
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# FINAL EVALUATION ON TEST SET\n",
            "# ============================================\n",
            "\n",
            "# Evaluate all models on test set\n",
            "test_results = {}\n",
            "\n",
            "print(\"Test Set Evaluation:\")\n",
            "print(\"=\" * 70)\n",
            "\n",
            "for name, model in trained_models.items():\n",
            "    # Predict on test set\n",
            "    y_test_pred = model.predict(X_test_scaled)\n",
            "    \n",
            "    # Calculate metrics\n",
            "    rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))\n",
            "    mae = mean_absolute_error(y_test, y_test_pred)\n",
            "    r2 = r2_score(y_test, y_test_pred)\n",
            "    mape = np.mean(np.abs((y_test - y_test_pred) / (y_test + 1e-10))) * 100\n",
            "    \n",
            "    test_results[name] = {\n",
            "        'RMSE': rmse,\n",
            "        'MAE': mae,\n",
            "        'R2': r2,\n",
            "        'MAPE': mape,\n",
            "        'predictions': y_test_pred\n",
            "    }\n",
            "    \n",
            "    print(f\"\\n{name}:\")\n",
            "    print(f\"  RMSE: {rmse:.2f}%\")\n",
            "    print(f\"  MAE:  {mae:.2f}%\")\n",
            "    print(f\"  R²:   {r2:.4f}\")\n",
            "    print(f\"  MAPE: {mape:.2f}%\")\n",
            "\n",
            "# Create results DataFrame\n",
            "test_results_df = pd.DataFrame({k: {m: v for m, v in v.items() if m != 'predictions'} \n",
            "                                for k, v in test_results.items()}).T\n",
            "test_results_df = test_results_df.sort_values('RMSE')\n",
            "\n",
            "print(\"\\n\" + \"=\" * 70)\n",
            "print(\"\\nTest Results Summary:\")\n",
            "display(test_results_df.style.background_gradient(cmap='RdYlGn_r', subset=['RMSE', 'MAE', 'MAPE'])\n",
            "                              .background_gradient(cmap='RdYlGn', subset=['R2']))\n",
            "\n",
            "best_test_model = test_results_df.index[0]\n",
            "print(f\"\\n🏆 Best Model on Test Set: {best_test_model}\")\n",
            "print(f\"   RMSE: {test_results_df.loc[best_test_model, 'RMSE']:.2f}%\")\n",
            "print(f\"   R²:   {test_results_df.loc[best_test_model, 'R2']:.4f}\")\n"
        ]
    },
    
    # Cell: Markdown - Prediction Visualization
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 11. Prediction Visualization\n",
            "\n",
            "### Visualizations to Create:\n",
            "\n",
            "1. **Actual vs Predicted Plot**: Shows how well predictions match reality\n",
            "2. **Time-Series Plot**: Shows RUL predictions over time\n",
            "3. **Error Distribution**: Shows where model makes mistakes\n",
            "4. **Residual Plot**: Checks for systematic errors\n",
            "\n",
            "### What to Look For:\n",
            "- **Good predictions**: Points close to diagonal line\n",
            "- **Systematic bias**: Points consistently above/below diagonal\n",
            "- **Heteroscedasticity**: Error variance changes with RUL\n"
        ]
    },
    
    # Cell: Code - Visualizations
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# PREDICTION VISUALIZATIONS\n",
            "# ============================================\n",
            "\n",
            "# Use best model for detailed visualization\n",
            "best_model = trained_models[best_test_model]\n",
            "y_pred_best = test_results[best_test_model]['predictions']\n",
            "\n",
            "# Create comprehensive visualization\n",
            "fig = plt.figure(figsize=(18, 12))\n",
            "gs = fig.add_gridspec(3, 2, hspace=0.3, wspace=0.3)\n",
            "\n",
            "# 1. Actual vs Predicted (all models)\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "for name in trained_models.keys():\n",
            "    y_pred = test_results[name]['predictions']\n",
            "    ax1.scatter(y_test, y_pred, alpha=0.5, s=20, label=name)\n",
            "ax1.plot([0, 100], [0, 100], 'k--', lw=2, label='Perfect Prediction')\n",
            "ax1.set_xlabel('Actual RUL (%)', fontsize=12)\n",
            "ax1.set_ylabel('Predicted RUL (%)', fontsize=12)\n",
            "ax1.set_title('Actual vs Predicted RUL - All Models', fontsize=14, fontweight='bold')\n",
            "ax1.legend()\n",
            "ax1.grid(True, alpha=0.3)\n",
            "\n",
            "# 2. Time-series prediction (best model)\n",
            "ax2 = fig.add_subplot(gs[1, 0])\n",
            "test_indices = np.arange(len(y_test))\n",
            "ax2.plot(test_indices, y_test, 'b-', linewidth=2, label='Actual RUL', alpha=0.7)\n",
            "ax2.plot(test_indices, y_pred_best, 'r--', linewidth=2, label='Predicted RUL', alpha=0.7)\n",
            "ax2.fill_between(test_indices, y_test, y_pred_best, alpha=0.2, color='gray')\n",
            "ax2.set_xlabel('Test Sample Index (Time)', fontsize=12)\n",
            "ax2.set_ylabel('RUL (%)', fontsize=12)\n",
            "ax2.set_title(f'RUL Prediction Over Time - {best_test_model}', fontsize=12, fontweight='bold')\n",
            "ax2.legend()\n",
            "ax2.grid(True, alpha=0.3)\n",
            "\n",
            "# 3. Error distribution\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "errors = y_test - y_pred_best\n",
            "ax3.hist(errors, bins=50, edgecolor='black', alpha=0.7, color='coral')\n",
            "ax3.axvline(x=0, color='red', linestyle='--', linewidth=2, label='Zero Error')\n",
            "ax3.axvline(x=errors.mean(), color='green', linestyle='--', linewidth=2, \n",
            "            label=f'Mean Error: {errors.mean():.2f}%')\n",
            "ax3.set_xlabel('Prediction Error (%)', fontsize=12)\n",
            "ax3.set_ylabel('Frequency', fontsize=12)\n",
            "ax3.set_title('Error Distribution', fontsize=12, fontweight='bold')\n",
            "ax3.legend()\n",
            "ax3.grid(True, alpha=0.3, axis='y')\n",
            "\n",
            "# 4. Residual plot\n",
            "ax4 = fig.add_subplot(gs[2, 0])\n",
            "ax4.scatter(y_pred_best, errors, alpha=0.5, s=30)\n",
            "ax4.axhline(y=0, color='red', linestyle='--', linewidth=2)\n",
            "ax4.set_xlabel('Predicted RUL (%)', fontsize=12)\n",
            "ax4.set_ylabel('Residual (Actual - Predicted)', fontsize=12)\n",
            "ax4.set_title('Residual Plot', fontsize=12, fontweight='bold')\n",
            "ax4.grid(True, alpha=0.3)\n",
            "\n",
            "# 5. Absolute error vs RUL\n",
            "ax5 = fig.add_subplot(gs[2, 1])\n",
            "abs_errors = np.abs(errors)\n",
            "ax5.scatter(y_test, abs_errors, alpha=0.5, s=30, c=y_test, cmap='viridis')\n",
            "ax5.set_xlabel('Actual RUL (%)', fontsize=12)\n",
            "ax5.set_ylabel('Absolute Error (%)', fontsize=12)\n",
            "ax5.set_title('Absolute Error vs RUL', fontsize=12, fontweight='bold')\n",
            "ax5.grid(True, alpha=0.3)\n",
            "cbar = plt.colorbar(ax5.collections[0], ax=ax5)\n",
            "cbar.set_label('RUL (%)', fontsize=10)\n",
            "\n",
            "plt.suptitle(f'Comprehensive Prediction Analysis - {best_test_model}', \n",
            "             fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.show()\n",
            "\n",
            "# Print error statistics\n",
            "print(f\"\\nError Statistics for {best_test_model}:\")\n",
            "print(f\"  Mean Error:     {errors.mean():.2f}%\")\n",
            "print(f\"  Std Error:      {errors.std():.2f}%\")\n",
            "print(f\"  Max Error:      {errors.max():.2f}%\")\n",
            "print(f\"  Min Error:      {errors.min():.2f}%\")\n",
            "print(f\"  Mean Abs Error: {abs_errors.mean():.2f}%\")\n"
        ]
    },
    
    # Cell: Markdown - Model Saving
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 12. Save Trained Models\n",
            "\n",
            "### Model Saving Strategy:\n",
            "\n",
            "**For ML Models (Scikit-learn)**: Use `.pkl` (pickle) format\n",
            "```python\n",
            "import joblib\n",
            "joblib.dump(model, 'model.pkl')\n",
            "```\n",
            "\n",
            "**For DL Models (Keras/TensorFlow)**: Use `.h5` format\n",
            "```python\n",
            "model.save('model.h5')\n",
            "```\n",
            "\n",
            "### What Gets Saved:\n",
            "- Model architecture and parameters\n",
            "- Trained weights\n",
            "- Hyperparameters\n",
            "\n",
            "### What to Save Separately:\n",
            "- **Scaler**: Must use same scaling for new predictions!\n",
            "- **Feature names**: To ensure correct feature order\n",
            "- **Metadata**: Training date, dataset info, performance metrics\n"
        ]
    },
    
    # Cell: Code - Save models
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# SAVE TRAINED MODELS\n",
            "# ============================================\n",
            "\n",
            "import joblib\n",
            "import json\n",
            "from datetime import datetime\n",
            "\n",
            "# Create models directory\n",
            "models_dir = '../models/nasa_ml'\n",
            "os.makedirs(models_dir, exist_ok=True)\n",
            "\n",
            "# Save all trained models\n",
            "print(\"Saving models...\\n\")\n",
            "for name, model in trained_models.items():\n",
            "    # Create safe filename\n",
            "    filename = name.lower().replace(' ', '_')\n",
            "    model_path = os.path.join(models_dir, f'{filename}.pkl')\n",
            "    \n",
            "    # Save model\n",
            "    joblib.dump(model, model_path)\n",
            "    file_size = os.path.getsize(model_path) / 1024  # KB\n",
            "    \n",
            "    print(f\"✓ Saved {name}\")\n",
            "    print(f\"  Path: {model_path}\")\n",
            "    print(f\"  Size: {file_size:.2f} KB\")\n",
            "    print()\n",
            "\n",
            "# Save scaler (CRITICAL for deployment!)\n",
            "scaler_path = os.path.join(models_dir, 'scaler.pkl')\n",
            "joblib.dump(scaler, scaler_path)\n",
            "print(f\"✓ Saved Feature Scaler\")\n",
            "print(f\"  Path: {scaler_path}\\n\")\n",
            "\n",
            "# Save feature names\n",
            "feature_names = features_df.drop('RUL', axis=1).columns.tolist()\n",
            "features_path = os.path.join(models_dir, 'feature_names.json')\n",
            "with open(features_path, 'w') as f:\n",
            "    json.dump(feature_names, f, indent=2)\n",
            "print(f\"✓ Saved Feature Names\")\n",
            "print(f\"  Path: {features_path}\\n\")\n",
            "\n",
            "# Save metadata\n",
            "metadata = {\n",
            "    'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),\n",
            "    'dataset': 'NASA IMS Bearing - 1st Test',\n",
            "    'total_samples': len(features_df),\n",
            "    'num_features': len(feature_names),\n",
            "    'test_results': test_results_df.to_dict(),\n",
            "    'best_model': best_test_model,\n",
            "    'best_rmse': float(test_results_df.loc[best_test_model, 'RMSE']),\n",
            "    'best_r2': float(test_results_df.loc[best_test_model, 'R2'])\n",
            "}\n",
            "\n",
            "metadata_path = os.path.join(models_dir, 'metadata.json')\n",
            "with open(metadata_path, 'w') as f:\n",
            "    json.dump(metadata, f, indent=2)\n",
            "print(f\"✓ Saved Metadata\")\n",
            "print(f\"  Path: {metadata_path}\\n\")\n",
            "\n",
            "print(\"=\" * 60)\n",
            "print(\"All models saved successfully!\")\n",
            "print(f\"\\nTo load a model:\")\n",
            "print(f\"  model = joblib.load('{models_dir}/random_forest.pkl')\")\n",
            "print(f\"  scaler = joblib.load('{scaler_path}')\")\n"
        ]
    },
    
    # Cell: Markdown - Summary
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 13. Summary and Next Steps\n",
            "\n",
            "### What We Accomplished:\n",
            "\n",
            "✅ **Data Exploration**:\n",
            "- Loaded NASA IMS bearing dataset\n",
            "- Analyzed 2000+ files of run-to-failure data\n",
            "- Visualized degradation patterns\n",
            "\n",
            "✅ **RUL Label Creation**:\n",
            "- Implemented linear degradation model\n",
            "- Created RUL labels (0-100%)\n",
            "\n",
            "✅ **Feature Engineering**:\n",
            "- Extracted 12 features per bearing (48 total)\n",
            "- Time-domain: RMS, kurtosis, skewness, etc.\n",
            "- Frequency-domain: Spectral centroid, spread, entropy\n",
            "\n",
            "✅ **ML Model Training**:\n",
            "- Trained 4 regression models\n",
            "- Compared performance\n",
            "- Selected best model\n",
            "\n",
            "✅ **Evaluation**:\n",
            "- Comprehensive metrics (RMSE, MAE, R², MAPE)\n",
            "- Visualization of predictions\n",
            "- Error analysis\n",
            "\n",
            "✅ **Model Deployment**:\n",
            "- Saved all models (.pkl)\n",
            "- Saved scaler and feature names\n",
            "- Created metadata for reproducibility\n",
            "\n",
            "### Next Steps:\n",
            "\n",
            "1. **Deep Learning (LSTM)**:\n",
            "   - Create `02_NASA_DL_LSTM_training.ipynb`\n",
            "   - Use time-series sequences\n",
            "   - Compare with ML models\n",
            "\n",
            "2. **Multi-Test Validation**:\n",
            "   - Train on 1st_test, validate on 2nd_test and 3rd_test\n",
            "   - Check generalization across different runs\n",
            "\n",
            "3. **Advanced Features**:\n",
            "   - Wavelet transforms\n",
            "   - Envelope spectrum\n",
            "   - Order tracking\n",
            "\n",
            "4. **Integration**:\n",
            "   - Update `src/interface.py` to use trained models\n",
            "   - Add RUL prediction capability\n",
            "   - Implement uncertainty quantification\n",
            "\n",
            "### Key Insights:\n",
            "\n",
            "- **Best Model**: Typically Gradient Boosting or Random Forest\n",
            "- **RMSE**: Should be < 20% for good RUL prediction\n",
            "- **Challenge**: Late-life prediction (low RUL) is harder\n",
            "- **Improvement**: LSTM may capture temporal patterns better\n"
        ]
    }
]

# Add cells
nb['cells'].extend(final_cells)

# Save
with open('notebooks/02_NASA_ML_training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4, ensure_ascii=False)

print(f"Added {len(final_cells)} final cells")
print("Notebook complete with all sections!")
print("\\nTotal sections:")
print("  1. Imports & Setup")
print("  2. Data Exploration")
print("  3. RUL Label Creation")
print("  4. Feature Extraction")
print("  5. Extract All Features")
print("  6. Train/Val/Test Split")
print("  7. Feature Scaling")
print("  8. ML Model Training")
print("  9. Model Comparison")
print(" 10. Test Evaluation")
print(" 11. Prediction Visualization")
print(" 12. Model Saving")
print(" 13. Summary")
