"""
Script to add remaining cells to NASA ML training notebook
"""
import json

# Load the existing notebook
with open('notebooks/02_NASA_ML_training.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Additional cells to add
new_cells = [
    # Cell: Markdown - Train/Val/Test Split
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Train-Validation-Test Split\n",
            "\n",
            "### Split Strategy for Time-Series Data:\n",
            "\n",
            "**Important**: Unlike random splits, we must preserve temporal order!\n",
            "\n",
            "```\n",
            "Time →\n",
            "[Early files] → [Middle files] → [Late files]\n",
            "   Training         Validation        Test\n",
            "    (60%)             (20%)           (20%)\n",
            "```\n",
            "\n",
            "### Why Temporal Split?\n",
            "- **Random split**: Model sees future data during training (data leakage!)\n",
            "- **Temporal split**: Model trained on early data, tested on later data (realistic)\n",
            "\n",
            "### Split Ratios:\n",
            "- **Training (60%)**: Early operational life (high RUL)\n",
            "- **Validation (20%)**: Middle life (medium RUL)\n",
            "- **Test (20%)**: Late life (low RUL) - most critical for prediction!\n"
        ]
    },
    
    # Cell: Code - Split data
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# TRAIN-VALIDATION-TEST SPLIT (TEMPORAL)\n",
            "# ============================================\n",
            "\n",
            "# Separate features and target\n",
            "X = features_df.drop('RUL', axis=1).values  # Features\n",
            "y = features_df['RUL'].values                # Target (RUL)\n",
            "\n",
            "# Calculate split indices (temporal order preserved)\n",
            "n_samples = len(X)\n",
            "train_end = int(0.6 * n_samples)\n",
            "val_end = int(0.8 * n_samples)\n",
            "\n",
            "# Split data\n",
            "X_train = X[:train_end]\n",
            "y_train = y[:train_end]\n",
            "\n",
            "X_val = X[train_end:val_end]\n",
            "y_val = y[train_end:val_end]\n",
            "\n",
            "X_test = X[val_end:]\n",
            "y_test = y[val_end:]\n",
            "\n",
            "print(\"Dataset Split (Temporal):\")\n",
            "print(f\"  Training:   {X_train.shape[0]} samples ({X_train.shape[0]/n_samples*100:.1f}%)\")\n",
            "print(f\"  Validation: {X_val.shape[0]} samples ({X_val.shape[0]/n_samples*100:.1f}%)\")\n",
            "print(f\"  Test:       {X_test.shape[0]} samples ({X_test.shape[0]/n_samples*100:.1f}%)\")\n",
            "\n",
            "print(\"\\nRUL Distribution:\")\n",
            "print(f\"  Train - Mean RUL: {y_train.mean():.2f}%, Range: [{y_train.min():.1f}, {y_train.max():.1f}]\")\n",
            "print(f\"  Val   - Mean RUL: {y_val.mean():.2f}%, Range: [{y_val.min():.1f}, {y_val.max():.1f}]\")\n",
            "print(f\"  Test  - Mean RUL: {y_test.mean():.2f}%, Range: [{y_test.min():.1f}, {y_test.max():.1f}]\")\n",
            "\n",
            "# Visualize split\n",
            "plt.figure(figsize=(14, 5))\n",
            "plt.plot(y, label='All Data', linewidth=2, alpha=0.7)\n",
            "plt.axvline(x=train_end, color='green', linestyle='--', label='Train/Val Split', linewidth=2)\n",
            "plt.axvline(x=val_end, color='orange', linestyle='--', label='Val/Test Split', linewidth=2)\n",
            "plt.xlabel('Sample Index (Time)', fontsize=12)\n",
            "plt.ylabel('RUL (%)', fontsize=12)\n",
            "plt.title('Temporal Data Split for Time-Series RUL Prediction', fontsize=14, fontweight='bold')\n",
            "plt.legend(fontsize=11)\n",
            "plt.grid(True, alpha=0.3)\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]
    },
    
    # Cell: Markdown - Feature Scaling
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Feature Scaling\n",
            "\n",
            "### Why Scale Features?\n",
            "\n",
            "Different features have different scales:\n",
            "- RMS: 0.01 - 0.5\n",
            "- Spectral Centroid: 1000 - 5000 Hz\n",
            "- Kurtosis: 2 - 10\n",
            "\n",
            "### Problems Without Scaling:\n",
            "- **SVR**: Very sensitive to feature scales\n",
            "- **Gradient Boosting**: Less affected but still benefits\n",
            "- **Random Forest**: Not affected (tree-based)\n",
            "\n",
            "### StandardScaler:\n",
            "Transforms features to have:\n",
            "- Mean = 0\n",
            "- Standard Deviation = 1\n",
            "\n",
            "**Important**: Fit scaler on training data only, then transform all sets!\n"
        ]
    },
    
    # Cell: Code - Feature scaling
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# FEATURE SCALING\n",
            "# ============================================\n",
            "\n",
            "# Initialize scaler\n",
            "scaler = StandardScaler()\n",
            "\n",
            "# Fit on training data ONLY (to avoid data leakage)\n",
            "scaler.fit(X_train)\n",
            "\n",
            "# Transform all sets using the same scaler\n",
            "X_train_scaled = scaler.transform(X_train)\n",
            "X_val_scaled = scaler.transform(X_val)\n",
            "X_test_scaled = scaler.transform(X_test)\n",
            "\n",
            "print(\"Feature Scaling Complete!\")\n",
            "print(f\"\\nScaled Training Data:\")\n",
            "print(f\"  Mean: {X_train_scaled.mean(axis=0).mean():.6f} (should be ≈0)\")\n",
            "print(f\"  Std:  {X_train_scaled.std(axis=0).mean():.6f} (should be ≈1)\")\n",
            "\n",
            "# Compare before and after scaling (first feature)\n",
            "feature_idx = 0\n",
            "feature_name = features_df.columns[feature_idx]\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "# Before scaling\n",
            "axes[0].hist(X_train[:, feature_idx], bins=50, edgecolor='black', alpha=0.7)\n",
            "axes[0].set_title(f'Before Scaling: {feature_name}', fontsize=12, fontweight='bold')\n",
            "axes[0].set_xlabel('Value')\n",
            "axes[0].set_ylabel('Frequency')\n",
            "axes[0].grid(True, alpha=0.3)\n",
            "\n",
            "# After scaling\n",
            "axes[1].hist(X_train_scaled[:, feature_idx], bins=50, edgecolor='black', alpha=0.7, color='green')\n",
            "axes[1].set_title(f'After Scaling: {feature_name}', fontsize=12, fontweight='bold')\n",
            "axes[1].set_xlabel('Scaled Value')\n",
            "axes[1].set_ylabel('Frequency')\n",
            "axes[1].grid(True, alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]
    },
    
    # Cell: Markdown - ML Model Training
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 8. Train ML Regression Models\n",
            "\n",
            "### Models to Train:\n",
            "\n",
            "| Model | Type | Strengths | Weaknesses |\n",
            "|-------|------|-----------|------------|\n",
            "| **Linear Regression** | Linear | Fast, interpretable | Too simple for complex patterns |\n",
            "| **Random Forest** | Ensemble (Trees) | Robust, handles non-linearity | Can overfit, slower |\n",
            "| **Gradient Boosting** | Ensemble (Boosting) | High accuracy, captures complex patterns | Prone to overfitting, needs tuning |\n",
            "| **SVR** | Kernel-based | Good for small datasets, non-linear | Slow on large data, sensitive to scaling |\n",
            "\n",
            "### Training Strategy:\n",
            "1. Train each model on training set\n",
            "2. Validate on validation set\n",
            "3. Select best model\n",
            "4. Final evaluation on test set\n"
        ]
    },
    
    # Cell: Code - Train models
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# TRAIN ML MODELS\n",
            "# ============================================\n",
            "\n",
            "# Initialize models\n",
            "models = {\n",
            "    'Linear Regression': LinearRegression(),\n",
            "    'Random Forest': RandomForestRegressor(\n",
            "        n_estimators=100,      # Number of trees\n",
            "        max_depth=20,          # Maximum tree depth\n",
            "        min_samples_split=5,   # Minimum samples to split\n",
            "        random_state=42,\n",
            "        n_jobs=-1              # Use all CPU cores\n",
            "    ),\n",
            "    'Gradient Boosting': GradientBoostingRegressor(\n",
            "        n_estimators=100,      # Number of boosting stages\n",
            "        learning_rate=0.1,     # Shrinks contribution of each tree\n",
            "        max_depth=5,           # Maximum tree depth\n",
            "        random_state=42\n",
            "    ),\n",
            "    'SVR': SVR(\n",
            "        kernel='rbf',          # Radial Basis Function kernel\n",
            "        C=100,                 # Regularization parameter\n",
            "        epsilon=0.1            # Epsilon-tube width\n",
            "    )\n",
            "}\n",
            "\n",
            "# Train all models\n",
            "trained_models = {}\n",
            "training_results = {}\n",
            "\n",
            "print(\"Training Models...\\n\")\n",
            "for name, model in models.items():\n",
            "    print(f\"Training {name}...\")\n",
            "    \n",
            "    # Train model\n",
            "    model.fit(X_train_scaled, y_train)\n",
            "    \n",
            "    # Predict on validation set\n",
            "    y_val_pred = model.predict(X_val_scaled)\n",
            "    \n",
            "    # Calculate metrics\n",
            "    rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))\n",
            "    mae = mean_absolute_error(y_val, y_val_pred)\n",
            "    r2 = r2_score(y_val, y_val_pred)\n",
            "    \n",
            "    # Store results\n",
            "    trained_models[name] = model\n",
            "    training_results[name] = {\n",
            "        'RMSE': rmse,\n",
            "        'MAE': mae,\n",
            "        'R2': r2\n",
            "    }\n",
            "    \n",
            "    print(f\"  Validation RMSE: {rmse:.2f}%\")\n",
            "    print(f\"  Validation MAE:  {mae:.2f}%\")\n",
            "    print(f\"  Validation R²:   {r2:.4f}\")\n",
            "    print()\n",
            "\n",
            "print(\"✓ All models trained!\")\n"
        ]
    },
    
    # Cell: Markdown - Model Comparison
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 9. Model Comparison\n",
            "\n",
            "### Evaluation Metrics Explained:\n",
            "\n",
            "#### RMSE (Root Mean Squared Error):\n",
            "- Average prediction error in RUL%\n",
            "- **Lower is better**\n",
            "- Penalizes large errors more heavily\n",
            "- Example: RMSE = 10% means predictions are off by ±10% on average\n",
            "\n",
            "#### MAE (Mean Absolute Error):\n",
            "- Average absolute prediction error\n",
            "- **Lower is better**\n",
            "- More robust to outliers than RMSE\n",
            "\n",
            "#### R² Score (Coefficient of Determination):\n",
            "- How well model explains variance in data\n",
            "- **Range**: -∞ to 1.0\n",
            "- **1.0** = Perfect predictions\n",
            "- **0.0** = Model as good as predicting mean\n",
            "- **< 0** = Model worse than predicting mean\n"
        ]
    },
    
    # Cell: Code - Compare models
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# COMPARE MODEL PERFORMANCE\n",
            "# ============================================\n",
            "\n",
            "# Create comparison DataFrame\n",
            "results_df = pd.DataFrame(training_results).T\n",
            "results_df = results_df.sort_values('RMSE')  # Sort by RMSE (lower is better)\n",
            "\n",
            "print(\"Model Performance Comparison (Validation Set):\")\n",
            "print(\"=\" * 60)\n",
            "display(results_df.style.background_gradient(cmap='RdYlGn_r', subset=['RMSE', 'MAE'])\n",
            "                        .background_gradient(cmap='RdYlGn', subset=['R2']))\n",
            "\n",
            "# Visualize comparison\n",
            "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
            "\n",
            "# RMSE comparison\n",
            "axes[0].bar(results_df.index, results_df['RMSE'], color='coral', edgecolor='black')\n",
            "axes[0].set_title('RMSE Comparison (Lower is Better)', fontsize=12, fontweight='bold')\n",
            "axes[0].set_ylabel('RMSE (%)')\n",
            "axes[0].tick_params(axis='x', rotation=45)\n",
            "axes[0].grid(True, alpha=0.3, axis='y')\n",
            "\n",
            "# MAE comparison\n",
            "axes[1].bar(results_df.index, results_df['MAE'], color='skyblue', edgecolor='black')\n",
            "axes[1].set_title('MAE Comparison (Lower is Better)', fontsize=12, fontweight='bold')\n",
            "axes[1].set_ylabel('MAE (%)')\n",
            "axes[1].tick_params(axis='x', rotation=45)\n",
            "axes[1].grid(True, alpha=0.3, axis='y')\n",
            "\n",
            "# R² comparison\n",
            "axes[2].bar(results_df.index, results_df['R2'], color='lightgreen', edgecolor='black')\n",
            "axes[2].set_title('R² Score Comparison (Higher is Better)', fontsize=12, fontweight='bold')\n",
            "axes[2].set_ylabel('R² Score')\n",
            "axes[2].tick_params(axis='x', rotation=45)\n",
            "axes[2].axhline(y=0.8, color='red', linestyle='--', label='Good (0.8)', alpha=0.7)\n",
            "axes[2].legend()\n",
            "axes[2].grid(True, alpha=0.3, axis='y')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Identify best model\n",
            "best_model_name = results_df.index[0]\n",
            "print(f\"\\n🏆 Best Model: {best_model_name}\")\n",
            "print(f\"   RMSE: {results_df.loc[best_model_name, 'RMSE']:.2f}%\")\n",
            "print(f\"   R²:   {results_df.loc[best_model_name, 'R2']:.4f}\")\n"
        ]
    }
]

# Add new cells to notebook
nb['cells'].extend(new_cells)

# Save updated notebook
with open('notebooks/02_NASA_ML_training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4, ensure_ascii=False)

print(f"Added {len(new_cells)} cells to notebook")
print("Notebook sections: Data exploration, RUL labels, Features, Splitting, Scaling, Training, Comparison")
