"""
Add detailed comments to code cells in the CNN training notebook
"""
import json

# Load the notebook
with open('notebooks/01_DL_cnn_training.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Enhanced code with comments for each code cell
enhanced_code = {
    1: [  # Imports cell
        "# ============================================\n",
        "# IMPORTS AND SETUP\n",
        "# ============================================\n",
        "import sys\n",
        "import os\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "# Auto-reload modules (useful for development)\n",
        "%load_ext autoreload\n",
        "%autoreload 2\n",
        "\n",
        "# Add parent directory to path so we can import from src/\n",
        "sys.path.append(os.path.abspath(os.path.join('..')))\n",
        "\n",
        "# Import our custom modules\n",
        "from src.data.loaders import CWRULoader  # For loading CWRU bearing data\n",
        "from src.models.cnn_classifier import CNN1DClassifier  # Our 1D CNN model\n",
        "\n",
        "print(f\"Python Version: {sys.version}\")\n"
    ],
    
    3: [  # Data loading cell
        "# ============================================\n",
        "# DATA LOADING\n",
        "# ============================================\n",
        "\n",
        "# Path to CWRU dataset\n",
        "DATA_DIR = r'../CWRU_Data'\n",
        "loader = CWRULoader(DATA_DIR)\n",
        "\n",
        "def create_raw_dataset(filenames, label, chunk_size=1000):\n",
        "    \"\"\"\n",
        "    Create dataset from raw signals (no feature extraction).\n",
        "    \n",
        "    Args:\n",
        "        filenames: List of .mat files to load\n",
        "        label: Class label (0=Normal, 1=Inner, 2=Ball, 3=Outer)\n",
        "        chunk_size: Number of samples per chunk (default 1000)\n",
        "    \n",
        "    Returns:\n",
        "        signals_list: List of signal chunks\n",
        "        labels_list: Corresponding labels\n",
        "    \"\"\"\n",
        "    signals_list = []\n",
        "    labels_list = []\n",
        "    \n",
        "    for filename in filenames:\n",
        "        try:\n",
        "            # Load the raw vibration signal from .mat file\n",
        "            signal = loader.load_file(filename)\n",
        "            \n",
        "            # Split long signal into fixed-size chunks\n",
        "            # This creates multiple training samples from one file\n",
        "            num_chunks = len(signal) // chunk_size\n",
        "            \n",
        "            for i in range(num_chunks):\n",
        "                # Extract chunk of signal\n",
        "                chunk = signal[i*chunk_size : (i+1)*chunk_size]\n",
        "                signals_list.append(chunk)\n",
        "                labels_list.append(label)  # Same label for all chunks from this file\n",
        "        except Exception as e:\n",
        "            print(f\"Error loading {filename}: {e}\")\n",
        "    \n",
        "    return signals_list, labels_list\n",
        "\n",
        "# Load data for each fault type\n",
        "print(\"Loading Raw Signal Data...\")\n",
        "\n",
        "# Normal (healthy) bearing data\n",
        "print(\"Normal Data...\")\n",
        "normal_files = ['97.mat', '98.mat', '99.mat', '100.mat']\n",
        "X_normal, y_normal = create_raw_dataset(normal_files, label=0)\n",
        "print(f\"Loaded {len(X_normal)} samples.\")\n",
        "\n",
        "# Inner race fault data\n",
        "print(\"Inner Race Data...\")\n",
        "inner_files = ['105.mat', '106.mat', '107.mat', '108.mat']\n",
        "X_inner, y_inner = create_raw_dataset(inner_files, label=1)\n",
        "print(f\"Loaded {len(X_inner)} samples.\")\n",
        "\n",
        "# Ball fault data\n",
        "print(\"Ball Fault Data...\")\n",
        "ball_files = ['118.mat', '119.mat', '120.mat', '121.mat']\n",
        "X_ball, y_ball = create_raw_dataset(ball_files, label=2)\n",
        "print(f\"Loaded {len(X_ball)} samples.\")\n",
        "\n",
        "# Outer race fault data\n",
        "print(\"Outer Race Data...\")\n",
        "outer_files = ['130.mat', '131.mat', '132.mat', '133.mat']\n",
        "X_outer, y_outer = create_raw_dataset(outer_files, label=3)\n",
        "print(f\"Loaded {len(X_outer)} samples.\")\n",
        "\n",
        "# Combine all data\n",
        "X_all = np.array(X_normal + X_inner + X_ball + X_outer)  # Shape: (n_samples, 1000)\n",
        "y_all = np.array(y_normal + y_inner + y_ball + y_outer)  # Shape: (n_samples,)\n",
        "\n",
        "print(f\"\\nTotal Dataset Shape: {X_all.shape}\")\n",
        "print(f\"Signal Length: {X_all.shape[1]} samples\")\n"
    ],
    
    5: [  # Normalization cell
        "# ============================================\n",
        "# DATA NORMALIZATION\n",
        "# ============================================\n",
        "\n",
        "# Normalize signals using Z-score normalization (per sample)\n",
        "# Formula: (x - mean) / std\n",
        "# This removes amplitude differences and focuses on signal shape\n",
        "X_normalized = (X_all - X_all.mean(axis=1, keepdims=True)) / (X_all.std(axis=1, keepdims=True) + 1e-8)\n",
        "#                      ↑ mean of each signal              ↑ std of each signal    ↑ avoid division by zero\n",
        "\n",
        "print(f\"Normalized Data Shape: {X_normalized.shape}\")\n",
        "print(f\"Mean: {X_normalized.mean():.6f} (should be ~0)\")\n",
        "print(f\"Std: {X_normalized.std():.6f} (should be ~1)\")\n"
    ],
    
    7: [  # Class distribution visualization
        "# ============================================\n",
        "# CLASS DISTRIBUTION ANALYSIS\n",
        "# ============================================\n",
        "\n",
        "# Define class names for better visualization\n",
        "class_names = ['Normal', 'Inner Race', 'Ball', 'Outer Race']\n",
        "\n",
        "# Count samples per class\n",
        "unique, counts = np.unique(y_all, return_counts=True)\n",
        "\n",
        "# Visualize class distribution\n",
        "plt.figure(figsize=(10, 5))\n",
        "\n",
        "# Bar plot\n",
        "plt.subplot(1, 2, 1)\n",
        "plt.bar(class_names, counts, color=['green', 'orange', 'red', 'purple'])\n",
        "plt.xlabel('Fault Type')\n",
        "plt.ylabel('Number of Samples')\n",
        "plt.title('Class Distribution (Before Balancing)')\n",
        "plt.xticks(rotation=45)\n",
        "\n",
        "# Pie chart\n",
        "plt.subplot(1, 2, 2)\n",
        "plt.pie(counts, labels=class_names, autopct='%1.1f%%', colors=['green', 'orange', 'red', 'purple'])\n",
        "plt.title('Class Distribution (Percentage)')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Print statistics\n",
        "print(\"\\nClass Distribution:\")\n",
        "for name, count in zip(class_names, counts):\n",
        "    print(f\"{name}: {count} samples ({count/len(y_all)*100:.1f}%)\")\n"
    ],
    
    8: [  # SMOTE balancing
        "# ============================================\n",
        "# CLASS BALANCING USING SMOTE\n",
        "# ============================================\n",
        "\n",
        "from imblearn.over_sampling import SMOTE\n",
        "\n",
        "# SMOTE requires 2D input, so we keep signals flattened\n",
        "# SMOTE works by:\n",
        "# 1. Finding k-nearest neighbors for minority class samples\n",
        "# 2. Creating synthetic samples by interpolating between neighbors\n",
        "# 3. Balancing all classes to have equal number of samples\n",
        "\n",
        "smote = SMOTE(random_state=42)\n",
        "X_balanced, y_balanced = smote.fit_resample(X_normalized, y_all)\n",
        "\n",
        "print(f\"Original shape: {X_normalized.shape}\")\n",
        "print(f\"Balanced shape: {X_balanced.shape}\")\n",
        "\n",
        "# Check new class distribution\n",
        "unique_balanced, counts_balanced = np.unique(y_balanced, return_counts=True)\n",
        "print(\"\\nBalanced Class Distribution:\")\n",
        "for name, count in zip(class_names, counts_balanced):\n",
        "    print(f\"{name}: {count} samples\")\n"
    ],
    
    10: [  # Train/val/test split
        "# ============================================\n",
        "# TRAIN-VALIDATION-TEST SPLIT\n",
        "# ============================================\n",
        "\n",
        "from sklearn.model_selection import train_test_split\n",
        "\n",
        "# First split: Separate test set (20%)\n",
        "# stratify=y_balanced ensures each set has same class distribution\n",
        "X_temp, X_test, y_temp, y_test = train_test_split(\n",
        "    X_balanced, y_balanced, \n",
        "    test_size=0.2,      # 20% for testing\n",
        "    random_state=42,    # For reproducibility\n",
        "    stratify=y_balanced # Keep class distribution\n",
        ")\n",
        "\n",
        "# Second split: Divide remaining into train (75%) and validation (25%)\n",
        "# This gives us 60% train, 20% val, 20% test overall\n",
        "X_train, X_val, y_train, y_val = train_test_split(\n",
        "    X_temp, y_temp,\n",
        "    test_size=0.25,     # 25% of remaining 80% = 20% overall\n",
        "    random_state=42,\n",
        "    stratify=y_temp\n",
        ")\n",
        "\n",
        "# Print split sizes\n",
        "print(f\"Training Set:   {X_train.shape[0]} samples ({X_train.shape[0]/len(X_balanced)*100:.1f}%)\")\n",
        "print(f\"Validation Set: {X_val.shape[0]} samples ({X_val.shape[0]/len(X_balanced)*100:.1f}%)\")\n",
        "print(f\"Test Set:       {X_test.shape[0]} samples ({X_test.shape[0]/len(X_balanced)*100:.1f}%)\")\n",
        "\n",
        "# Verify class distribution in each set\n",
        "print(\"\\nClass distribution in each set:\")\n",
        "for set_name, y_set in [('Train', y_train), ('Val', y_val), ('Test', y_test)]:\n",
        "    unique, counts = np.unique(y_set, return_counts=True)\n",
        "    print(f\"{set_name}: {dict(zip(class_names, counts))}\")\n"
    ],
    
    12: [  # Model initialization
        "# ============================================\n",
        "# BUILD CNN MODEL\n",
        "# ============================================\n",
        "\n",
        "# Initialize 1D CNN classifier\n",
        "# Parameters:\n",
        "#   - input_length: Length of input signal (1000 samples)\n",
        "#   - num_classes: Number of fault types to classify (4)\n",
        "cnn_model = CNN1DClassifier(\n",
        "    input_length=X_train.shape[1],  # 1000\n",
        "    num_classes=len(class_names)     # 4\n",
        ")\n",
        "\n",
        "print(\"CNN Model Architecture:\")\n",
        "print(cnn_model.model.summary())  # Display model structure\n"
    ],
    
    13: [  # Model training
        "# ============================================\n",
        "# TRAIN THE MODEL\n",
        "# ============================================\n",
        "\n",
        "# Train the CNN model\n",
        "# The model will:\n",
        "#   1. Learn to extract features from raw signals\n",
        "#   2. Use early stopping if validation loss doesn't improve\n",
        "#   3. Reduce learning rate if stuck in plateau\n",
        "#   4. Save best weights based on validation performance\n",
        "\n",
        "history = cnn_model.train(\n",
        "    X_train, y_train,           # Training data\n",
        "    X_val, y_val,               # Validation data (for monitoring)\n",
        "    epochs=50,                  # Maximum number of epochs\n",
        "    batch_size=64,              # Samples per gradient update\n",
        "    verbose=1                   # Show progress bar\n",
        ")\n",
        "\n",
        "print(\"\\nTraining completed!\")\n"
    ],
    
    15: [  # Plot training history
        "# ============================================\n",
        "# VISUALIZE TRAINING HISTORY\n",
        "# ============================================\n",
        "\n",
        "# Plot loss and accuracy curves\n",
        "# This helps us understand:\n",
        "#   - Is the model learning? (loss decreasing)\n",
        "#   - Is it overfitting? (train/val gap increasing)\n",
        "#   - When did early stopping trigger?\n",
        "\n",
        "cnn_model.plot_training_history()\n"
    ],
    
    17: [  # Model evaluation
        "# ============================================\n",
        "# EVALUATE ON TEST SET\n",
        "# ============================================\n",
        "\n",
        "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score\n",
        "\n",
        "# Get predictions on test set\n",
        "y_pred = cnn_model.predict(X_test)           # Predicted classes\n",
        "y_prob = cnn_model.predict_proba(X_test)     # Prediction probabilities\n",
        "\n",
        "# Calculate accuracy\n",
        "test_acc = accuracy_score(y_test, y_pred)\n",
        "print(f\"\\n=== CNN Test Accuracy: {test_acc:.4f} ===\")\n",
        "\n",
        "# Detailed classification report\n",
        "# Shows precision, recall, F1-score for each class\n",
        "print(\"\\n--- Classification Report ---\")\n",
        "print(classification_report(y_test, y_pred, target_names=class_names))\n",
        "\n",
        "# Confusion Matrix\n",
        "# Shows which classes are being confused with each other\n",
        "cm = confusion_matrix(y_test, y_pred)\n",
        "\n",
        "plt.figure(figsize=(10, 8))\n",
        "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', \n",
        "            xticklabels=class_names, yticklabels=class_names)\n",
        "plt.title('Confusion Matrix - 1D CNN')\n",
        "plt.ylabel('True Label')\n",
        "plt.xlabel('Predicted Label')\n",
        "plt.show()\n"
    ],
    
    19: [  # ROC curves
        "# ============================================\n",
        "# ROC CURVES (RECEIVER OPERATING CHARACTERISTIC)\n",
        "# ============================================\n",
        "\n",
        "from sklearn.metrics import roc_curve, auc\n",
        "from sklearn.preprocessing import label_binarize\n",
        "from itertools import cycle\n",
        "\n",
        "# Convert labels to binary format for multi-class ROC\n",
        "# Creates one binary classifier per class (One-vs-Rest)\n",
        "y_test_bin = label_binarize(y_test, classes=[0, 1, 2, 3])\n",
        "n_classes = y_test_bin.shape[1]\n",
        "\n",
        "# Compute ROC curve and AUC for each class\n",
        "fpr = dict()  # False Positive Rate\n",
        "tpr = dict()  # True Positive Rate\n",
        "roc_auc = dict()  # Area Under Curve\n",
        "\n",
        "for i in range(n_classes):\n",
        "    # Calculate ROC curve for this class\n",
        "    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_prob[:, i])\n",
        "    roc_auc[i] = auc(fpr[i], tpr[i])  # Calculate AUC\n",
        "\n",
        "# Plot ROC curves\n",
        "plt.figure(figsize=(10, 8))\n",
        "colors = cycle(['blue', 'red', 'green', 'orange'])\n",
        "\n",
        "for i, color in zip(range(n_classes), colors):\n",
        "    plt.plot(fpr[i], tpr[i], color=color, lw=2,\n",
        "             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')\n",
        "\n",
        "# Plot diagonal (random classifier)\n",
        "plt.plot([0, 1], [0, 1], 'k--', lw=2, label='Random (AUC = 0.50)')\n",
        "\n",
        "plt.xlim([0.0, 1.0])\n",
        "plt.ylim([0.0, 1.05])\n",
        "plt.xlabel('False Positive Rate')\n",
        "plt.ylabel('True Positive Rate')\n",
        "plt.title('ROC Curves - Multi-class Classification')\n",
        "plt.legend(loc=\"lower right\")\n",
        "plt.grid(alpha=0.3)\n",
        "plt.show()\n"
    ],
    
    21: [  # Save model
        "# ============================================\n",
        "# SAVE THE TRAINED MODEL\n",
        "# ============================================\n",
        "\n",
        "import os\n",
        "\n",
        "# Create models directory if it doesn't exist\n",
        "os.makedirs('../models', exist_ok=True)\n",
        "\n",
        "# Save the CNN model in HDF5 format (.h5)\n",
        "# This format is standard for Keras/TensorFlow models\n",
        "# It saves:\n",
        "#   - Model architecture (layers, connections)\n",
        "#   - Trained weights (learned parameters)\n",
        "#   - Optimizer state (for resuming training)\n",
        "#   - Training configuration (loss, metrics)\n",
        "\n",
        "model_path = '../models/cnn_model.h5'\n",
        "cnn_model.save(model_path)\n",
        "\n",
        "print(f\"Model saved to: {model_path}\")\n",
        "print(f\"File size: {os.path.getsize(model_path) / 1024:.2f} KB\")\n",
        "\n",
        "# To load the model later:\n",
        "# from tensorflow import keras\n",
        "# loaded_model = keras.models.load_model('models/cnn_model.h5')\n"
    ]
}

# Update code cells with enhanced comments
for cell_idx, new_code in enhanced_code.items():
    if cell_idx < len(nb['cells']) and nb['cells'][cell_idx]['cell_type'] == 'code':
        nb['cells'][cell_idx]['source'] = new_code

# Save the enhanced notebook
with open('notebooks/01_DL_cnn_training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4, ensure_ascii=False)

print("Successfully enhanced notebook!")
print(f"Enhanced {len(enhanced_code)} code cells with detailed comments")
