import json
import os

notebook_path = r"d:\Silas Document\UMaT\Year 4\Project work\Matlab_Project codes\notebooks\04_CIA1_DL_training.ipynb"

# The code to be injected into the notebook
ensemble_code = [
    "# ==========================================\n",
    "# ENSEMBLE METHODS - Combining ML and DL Models\n",
    "# ==========================================\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from xgboost import XGBClassifier\n",
    "from scipy import stats\n",
    "import numpy as np\n",
    "\n",
    "print('='*70)\n",
    "print('ENSEMBLE METHODS - Combining ML and DL Models')\n",
    "print('='*70)\n",
    "\n",
    "# Train ML models\n",
    "print('\\nTraining ML models for ensemble...')\n",
    "ml_models = {\n",
    "    'Random_Forest': RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42, class_weight='balanced'),\n",
    "    'SVM': SVC(C=1.0, kernel='rbf', probability=True, random_state=42, class_weight='balanced'),\n",
    "    'Gradient_Boosting': GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42),\n",
    "    'KNN': KNeighborsClassifier(n_neighbors=5, weights='distance'),\n",
    "    'XGBoost': XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42, use_label_encoder=False, eval_metric='logloss')\n",
    "}\n",
    "\n",
    "ml_predictions = {}\n",
    "ml_probabilities = {}\n",
    "\n",
    "for name, ml_model in ml_models.items():\n",
    "    print(f'  Training {name}...')\n",
    "    ml_model.fit(X_train_scaled, y_train_balanced)\n",
    "    ml_predictions[name] = ml_model.predict(X_test_scaled)\n",
    "    if hasattr(ml_model, 'predict_proba'):\n",
    "        ml_probabilities[name] = ml_model.predict_proba(X_test_scaled)\n",
    "    ml_acc = (ml_predictions[name] == y_test).mean()\n",
    "    print(f'    {name} Test Accuracy: {ml_acc:.4f}')\n",
    "\n",
    "print('\\nML models trained successfully!')\n",
    "\n",
    "# --- Ensemble Strategy 1: Simple Voting ---\n",
    "print('\\n' + '='*70)\n",
    "print('ENSEMBLE STRATEGY 1: Simple Voting')\n",
    "print('='*70)\n",
    "\n",
    "all_predictions = {}\n",
    "all_predictions.update(ml_predictions)\n",
    "\n",
    "# Add DL predictions from previous cells\n",
    "# Assuming 'results' dictionary exists from DL training\n",
    "for model_name, result in results.items():\n",
    "    all_predictions[model_name] = result['predictions']\n",
    "\n",
    "# Simple majority voting\n",
    "predictions_array = np.array(list(all_predictions.values()))\n",
    "voting_predictions = stats.mode(predictions_array, axis=0, keepdims=False)[0]\n",
    "voting_accuracy = (voting_predictions == y_test).mean()\n",
    "\n",
    "print(f'\\nSimple Voting Ensemble Accuracy: {voting_accuracy:.4f}')\n",
    "print(f'Number of models in ensemble: {len(all_predictions)}')\n",
    "\n",
    "# --- Ensemble Strategy 2: Weighted Voting ---\n",
    "print('\\n' + '='*70)\n",
    "print('ENSEMBLE STRATEGY 2: Weighted Voting')\n",
    "print('='*70)\n",
    "\n",
    "model_weights = {}\n",
    "for name, preds in all_predictions.items():\n",
    "    acc = (preds == y_test).mean()\n",
    "    model_weights[name] = acc\n",
    "\n",
    "print('\\nModel Weights (based on test accuracy):')\n",
    "for name, weight in sorted(model_weights.items(), key=lambda x: x[1], reverse=True):\n",
    "    print(f'  {name:25s}: {weight:.4f}')\n",
    "\n",
    "# Weighted voting\n",
    "num_classes = len(np.unique(y_test))\n",
    "weighted_votes = np.zeros((len(y_test), num_classes))\n",
    "for name, preds in all_predictions.items():\n",
    "    weight = model_weights[name]\n",
    "    for i, pred in enumerate(preds):\n",
    "        weighted_votes[i, pred] += weight\n",
    "\n",
    "weighted_predictions = np.argmax(weighted_votes, axis=1)\n",
    "weighted_accuracy = (weighted_predictions == y_test).mean()\n",
    "\n",
    "print(f'\\nWeighted Voting Ensemble Accuracy: {weighted_accuracy:.4f}')\n",
    "\n",
    "# --- Ensemble Strategy 3: Soft Voting ---\n",
    "print('\\n' + '='*70)\n",
    "print('ENSEMBLE STRATEGY 3: Soft Voting (Probability Averaging)')\n",
    "print('='*70)\n",
    "\n",
    "all_probabilities = {}\n",
    "all_probabilities.update(ml_probabilities)\n",
    "\n",
    "# Add DL probabilities\n",
    "for model_name, result in results.items():\n",
    "    # Handle reshaping for 1D_CNN if necessary\n",
    "    if model_name == '1D_CNN':\n",
    "         if len(X_test_scaled.shape) == 2:\n",
    "             X_input = X_test_scaled.reshape(-1, X_test_scaled.shape[1], 1)\n",
    "         else:\n",
    "             X_input = X_test_scaled\n",
    "    else:\n",
    "         X_input = X_test_scaled\n",
    "         \n",
    "    all_probabilities[model_name] = result['model'].predict(X_input, verbose=0)\n",
    "\n",
    "# Average probabilities\n",
    "avg_probabilities = np.mean(list(all_probabilities.values()), axis=0)\n",
    "soft_voting_predictions = np.argmax(avg_probabilities, axis=1)\n",
    "soft_voting_accuracy = (soft_voting_predictions == y_test).mean()\n",
    "\n",
    "print(f'\\nSoft Voting Ensemble Accuracy: {soft_voting_accuracy:.4f}')\n",
    "\n",
    "# --- Ensemble Strategy 4: Top-K Models ---\n",
    "print('\\n' + '='*70)\n",
    "print('ENSEMBLE STRATEGY 4: Top-K Best Models')\n",
    "print('='*70)\n",
    "\n",
    "top_k = 5\n",
    "sorted_models = sorted(model_weights.items(), key=lambda x: x[1], reverse=True)\n",
    "top_models = dict(sorted_models[:top_k])\n",
    "\n",
    "print(f'\\nTop {top_k} models selected:')\n",
    "for name, weight in top_models.items():\n",
    "    print(f'  {name:25s}: {weight:.4f}')\n",
    "\n",
    "topk_votes = np.zeros((len(y_test), num_classes))\n",
    "for name in top_models.keys():\n",
    "    preds = all_predictions[name]\n",
    "    for i, pred in enumerate(preds):\n",
    "        topk_votes[i, pred] += 1\n",
    "\n",
    "topk_predictions = np.argmax(topk_votes, axis=1)\n",
    "topk_accuracy = (topk_predictions == y_test).mean()\n",
    "\n",
    "print(f'\\nTop-{top_k} Ensemble Accuracy: {topk_accuracy:.4f}')\n",
    "\n",
    "# --- Summary & Visualization ---\n",
    "print('\\n' + '='*70)\n",
    "print('ENSEMBLE RESULTS SUMMARY')\n",
    "print('='*70)\n",
    "\n",
    "ensemble_results = {\n",
    "    'Simple Voting': voting_accuracy,\n",
    "    'Weighted Voting': weighted_accuracy,\n",
    "    'Soft Voting (Probabilities)': soft_voting_accuracy,\n",
    "    f'Top-{top_k} Models': topk_accuracy\n",
    "}\n",
    "\n",
    "for method, acc in sorted(ensemble_results.items(), key=lambda x: x[1], reverse=True):\n",
    "    print(f'{method:30s}: {acc:.4f}')\n",
    "\n",
    "best_ensemble = max(ensemble_results.items(), key=lambda x: x[1])\n",
    "print(f'\\nBest Ensemble Method: {best_ensemble[0]} ({best_ensemble[1]:.4f})')\n",
    "\n",
    "# Visualization\n",
    "print('\\n' + '='*70)\n",
    "print('VISUALIZING RESULTS')\n",
    "print('='*70)\n",
    "\n",
    "plt.figure(figsize=(14, 8))\n",
    "plot_data = model_weights.copy()\n",
    "plot_data.update(ensemble_results)\n",
    "sorted_plot_data = dict(sorted(plot_data.items(), key=lambda x: x[1], reverse=True))\n",
    "\n",
    "bars = plt.barh(list(sorted_plot_data.keys()), list(sorted_plot_data.values()), color='skyblue')\n",
    "plt.xlabel('Accuracy')\n",
    "plt.title('Model and Ensemble Accuracy Comparison')\n",
    "plt.xlim(0, 1.0)\n",
    "\n",
    "for i, (name, acc) in enumerate(sorted_plot_data.items()):\n",
    "    if name in ensemble_results:\n",
    "        bars[i].set_color('lightgreen')\n",
    "    plt.text(acc + 0.01, i, f'{acc:.4f}', va='center')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]

try:
    with open(notebook_path, 'r', encoding='utf-8') as f:
        notebook_data = json.load(f)

    new_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": ensemble_code
    }

    # Append the new cell to the notebook
    notebook_data['cells'].append(new_cell)

    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(notebook_data, f, indent=1)

    print("Successfully added Ensemble Methods cell to the notebook.")

except Exception as e:
    print(f"Error updating notebook: {e}")
